-- Insert sample employees
insert into employees (
  first_name,
  middle_name,
  last_name,
  display_name,
  email,
  position_id,
  address,
  site_id,
  manager_id,
  employment_type,
  start_date,
  department_id,
  picture_url
) values
  (
    'John',
    'Michael',
    'Smith',
    'John Smith',
    'john.smith@company.com',
    (select id from positions where name = 'Software Engineer'),
    '123 Tech Street, San Francisco, CA',
    (select id from sites where city = 'San Francisco'),
    null,
    'fullTime',
    '2023-01-15',
    (select id from departments where name = 'Engineering'),
    'https://example.com/john-smith.jpg'
  ),
  (
    'Sarah',
    'Elizabeth',
    'Johnson',
    'Sarah Johnson',
    'sarah.johnson@company.com',
    (select id from positions where name = 'Product Manager'),
    '456 Market Street, New York, NY',
    (select id from sites where city = 'New York'),
    null,
    'fullTime',
    '2023-02-01',
    (select id from departments where name = 'Product'),
    'https://example.com/sarah-johnson.jpg'
  ),
  (
    'David',
    'Robert',
    'Williams',
    'David Williams',
    'david.williams@company.com',
    (select id from positions where name = 'UX Designer'),
    '789 Design Avenue, London, UK',
    (select id from sites where city = 'London'),
    (select id from employees where email = 'sarah.johnson@company.com'),
    'fullTime',
    '2023-03-10',
    (select id from departments where name = 'Design'),
    'https://example.com/david-williams.jpg'
  ),
  (
    'Emily',
    'Anne',
    'Brown',
    'Emily Brown',
    'emily.brown@company.com',
    (select id from positions where name = 'Marketing Specialist'),
    '321 Brand Road, Berlin, Germany',
    (select id from sites where city = 'Berlin'),
    (select id from employees where email = 'sarah.johnson@company.com'),
    'partTime',
    '2023-04-05',
    (select id from departments where name = 'Marketing'),
    'https://example.com/emily-brown.jpg'
  ),
  (
    'Michael',
    'James',
    'Davis',
    'Michael Davis',
    'michael.davis@company.com',
    (select id from positions where name = 'Data Scientist'),
    '654 Data Lane, Tokyo, Japan',
    (select id from sites where city = 'Tokyo'),
    (select id from employees where email = 'john.smith@company.com'),
    'fullTime',
    '2023-05-20',
    (select id from departments where name = 'Data'),
    'https://example.com/michael-davis.jpg'
  );
